#include "Utils.h"

#define SUCESSO_CADASTRO -1
#define ERRO_CADASTRO_MATRICULA -2
#define ERRO_CADASTRO_SEXO -3
#define ERRO_DATA_INVALIDA -4
#define LISTA_VAZIA -5
#define SUCESSO_EXCLUSAO -6
#define NAO_ENCONTRADO -7